export const GET_SECOND_FEEDBACK_FORM = 'GET_SECOND_FEEDBACK_FORM';
export const SET_SECOND_FEEDBACK_FORM = 'SET_SECOND_FEEDBACK_FORM';
export const SAVE_SECOND_FEEDBACK_FORM_DATA = 'SAVE_SECOND_FEEDBACK_FORM_DATA';
export const SET_SHOW_SECOND_FEEDBACK_FORM_DATA =
  'SET_SHOW_SECOND_FEEDBACK_FORM_DATA';
